spring:
  application:
    name: SiparisYonetimSistemi
  profiles:
    default: dev
  web:
    resources:
      add-mappings: true

security:
  jwt:
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}
    secret: ${JWT_SECRET:}

redirect:
  forwardUrl: /

